Added the option to switch to use a tree view for groups
keycloak/keycloak-ui pull request #2970
Opened 2022-07-15 12:56 UTC by edewit

- initial version of the tree view
- added toolbar
- fixed spelling
- introduced view switcher
- fix onSelect
- add more context menus

fixes: #2926

2022-07-15 17:55 UTC, jonkoops commented on src/groups/components/CheckableTreeView.tsx
> +  const [state, setState] = useState<{
Why keep the entire thing inside of a single object instead of two separate states? Not saying one is better than the other, just curious.

2022-07-15 21:25 UTC, jonkoops commented on src/groups/components/CheckableTreeView.tsx
> +    const checked = (evt.target as HTMLInputElement).checked;
Created a PR to fix this type https://github.com/patternfly/patternfly-react/pull/7705.

2022-07-15 22:04 UTC, jonkoops requested changes

2022-07-15 22:04 UTC, jonkoops commented on src/groups/components/GroupTree.tsx
> +              setSelectedRows(items.reverse() as GroupRepresentation[])
Weird that this needs to be casted.

2022-07-15 22:04 UTC, jonkoops commented on src/groups/components/MoveDialog.tsx
> +      if (group !== undefined) {
Perhaps the implementations in the branches of this `if` statement could be split out into two separate functions to make this code more readable?

```ts
await (group ? updateExisting(group) : createAndUpdate(group));
```

2022-07-29 08:56 UTC, edewit commented on src/groups/components/DeleteGroup.tsx
> +      }
No it has to be done in order otherwise deleting the groups will not work you can't delete the child of a group when the parent is already deleted

2022-07-29 08:58 UTC, edewit commented on src/groups/components/GroupToolbar.tsx
> +              icon={<i className="fas fa-project-diagram"></i>}
because patternfly uses font awesome icons see: https://www.patternfly.org/v4/guidelines/icons/#all-icons

2022-08-02 06:15 UTC, edewit commented on src/groups/components/CheckableTreeView.tsx
> +    const checked = (evt.target as HTMLInputElement).checked;
can I update this already?

2022-08-02 06:20 UTC, edewit commented on src/groups/components/GroupTree.tsx
> +  groups
I do that here like this because I can chain it

2022-08-02 06:23 UTC, edewit commented on src/groups/components/GroupTree.tsx
> +              setSelectedRows(items.reverse() as GroupRepresentation[])
because it's a `TreeViewDataItem` it has more properties then a `GroupRepresentation`

2022-08-02 09:34 UTC, jonkoops commented on src/groups/components/GroupToolbar.tsx
> +              icon={<i className="fas fa-project-diagram"></i>}
Naturally, we want our bundle size to be as big as possible! Can you use the regular icon from `@patternfly/react-icons`?

2022-08-03 08:54 UTC, edewit commented on src/groups/components/GroupToolbar.tsx
> +              icon={<i className="fas fa-project-diagram"></i>}
aren't they included already? as you can see I only set a classname and it works that means the icons should already be there.

2022-08-04 18:35 UTC, ssilvert reviewed
This is really cool to see.  I tried it out and found a couple of bugs.

The icon for tree view doesn't show up properly.
<img width="419" alt="treeview" src="https://user-images.githubusercontent.com/507202/182926008-ef470795-9f73-43c2-9fc5-7a4ef2c210f4.png">

Also, if I check one box in a branch the whole branch is selected.  For instance, I click "b" here and all nodes are checked:
<img width="194" alt="nested" src="https://user-images.githubusercontent.com/507202/182926969-c0d51c75-522b-4c99-ac33-02efb28715a6.png">

2022-08-08 08:42 UTC, edewit commented
@ssilvert fixed the icon: 
![image](https://user-images.githubusercontent.com/51133/183377167-fc717e93-ebbc-4360-bdc5-68991bfc6207.png)

2022-08-08 08:50 UTC, edewit commented
@ssilvert if you only want to delete `b` you can do that by using the action menu

2022-08-08 08:50 UTC, xianli123 commented
It's really cool.

2022-08-08 18:41 UTC, ssilvert commented
> @ssilvert if you only want to delete `b` you can do that by using the action menu

I don't think it should select the entire branch.  It should only select the node I clicked and its children.

For instance I might have a tree like this:

root -> A -> B -> C
root -> M -> N -> O
root -> X -> Y -> Z

I want to delete A, N, and Z all at once using the top menu.  But I can't.

Or, we could just get rid of the selection boxes in tree view.  They might take up too much real estate anyway.

2022-08-09 07:20 UTC, edewit commented
Right okay, removed that now

2022-08-09 07:20 UTC, edewit commented
Right okay, removed that now

2022-08-09 08:33 UTC, jonkoops commented on src/groups/components/GroupToolbar.tsx
> +              icon={<i className="fas fa-project-diagram"></i>}
Yeah, apparently. Not a big fan of what PatternFly is doing here.

2022-08-09 08:34 UTC, jonkoops approved these changes

2022-08-10 04:28 UTC, xianli123 commented
> It should only select the node I clicked and its children.

I think it makes sense. And if it's possible, we can add a kebab menu at the end of each row. The kebab menu can include "Delete" and "Move to". What do you think?

2022-08-12 19:58 UTC, jonkoops commented
@edewit can this be merged or do some of the comments here need to be resolved?

2022-08-15 12:29 UTC, merged