Fix homepage URL rendering in client list (#3057)
keycloak/keycloak-ui pull request #3058
Opened 2022-08-04 23:40 UTC by thomasdarimont

Signed-off-by: Thomas Darimont <thomas.darimont@googlemail.com>

## Motivation

## Brief Description

## Verification Steps

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated

## Additional Notes

2022-08-05 09:18 UTC, jonkoops commented
@thomasdarimont could you point towards the issue this PR resolves or add a description to the PR?

2022-08-08 05:48 UTC, edewit commented on src/clients/ClientsSection.tsx
> +    }
```suggestion
    if (rootUrl.startsWith("http") && baseUrl) {
        return addTrailingSlash(rootUrl) + baseUrl.substring(1);
   }
   
   return rootUrl;
```

2022-08-08 05:48 UTC, edewit commented on src/clients/ClientsSection.tsx
> +    }
but shouldn't we test that baseUrl starts with a slash instead of always doing a `baseUrl.substring(1)`?

2022-08-08 10:09 UTC, jonkoops commented on src/clients/ClientsSection.tsx
> +    }
That's why I created the new [`joinPath`](https://github.com/keycloak/keycloak-admin-ui/blob/main/src/utils/joinPath.ts) utility :wink:

2022-08-08 10:16 UTC, jonkoops requested changes

2022-08-08 10:16 UTC, jonkoops commented on src/clients/ClientsSection.tsx
> +  const ClientHomePage = (client: ClientRepresentation) => {
Can we extract this logic somewhere and add some unit tests? With the amount of branches in this function it feels hard to refactor without accidentally making breaking changes.

2022-08-08 11:35 UTC, edewit commented on src/clients/ClientsSection.tsx
> +  const ClientHomePage = (client: ClientRepresentation) => {
:+1: seems that @thomasdarimont is already unsure if all cases are met...

2022-08-16 12:17 UTC, jonkoops approved these changes
Let's merge this now as it fixes an actual bug and create a task to add some tests for this later.

2022-08-16 12:18 UTC, merged

2022-08-18 14:30 UTC, edewit commented on src/clients/ClientsSection.tsx
> +    }
If I read this correctly it means when `baseUrl` is not set and rootUrl contains either `"${authBaseUrl}"` or `"${authAdminUrl}"` then we return `undefined`? @thomasdarimont