resource request parameter and audience in access token
keycloak/keycloak-ui pull request #3084
Opened 2022-08-09 09:44 UTC by cgeorgilakis

## Motivation
Related to https://github.com/keycloak/keycloak/issues/13614.
keycloak related PR: https://github.com/keycloak/keycloak/pull/13622 ( working only with it)

## Brief Description

## Verification Steps

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated

## Additional Notes
![defaultAudAdminConsole](https://user-images.githubusercontent.com/55974447/183618115-77ddef38-72f0-4eec-b81b-cecd79135311.PNG)

2022-08-09 10:04 UTC, jonkoops commented
@xianli123 could you help me out by designing a generic error page that informs the user that an error occurred and that the Admin UI could not be loaded?

2022-08-09 10:25 UTC, jonkoops requested changes

2022-08-09 10:25 UTC, jonkoops commented on src/realm-settings/TokensTab.tsx
> +                  placeholder="Default aud value"
This string will have to be localized.

2022-08-09 10:25 UTC, jonkoops commented on src/realm-settings/TokensTab.tsx
> +                  type="text"
The default for this should already be `text` so I believe this can be omitted.
```suggestion
```

2022-08-09 10:25 UTC, jonkoops commented on src/realm-settings/TokensTab.tsx
> +            id="default-aud-value-label"
This identifier is never used anywhere so it can be removed.
```suggestion
```

2022-08-09 10:25 UTC, jonkoops commented on src/realm-settings/TokensTab.tsx
> +                  id="default-aud-value"
The id here should match the `fieldId` of the encapsulating `FormGroup`.
```suggestion
                  id="defaultAudValue"
```

2022-08-09 10:25 UTC, jonkoops commented on src/realm-settings/TokensTab.tsx
> +              defaultValue={""}
Braces can be omitted if the value is a string literal.
```suggestion
              defaultValue=""
```

2022-08-09 10:28 UTC, jonkoops commented
Since this PR depends on upstream functionality (https://github.com/keycloak/keycloak/pull/13622) we'll have to hold off merging it until the functionality has landed upstream.

2022-08-09 11:33 UTC, cgeorgilakis commented
I have made the requested changes.
Of course, this PR can be on hold until [Keycloak PR](https://github.com/keycloak/keycloak/pull/13622) has been accepted.

2022-08-12 13:15 UTC, jonkoops approved these changes

2022-08-15 12:13 UTC, edewit approved these changes

2022-11-17 17:01 UTC, jonkoops commented
@cgeorgilakis I've asked @mposolda to review your PR on the main repo, hopefully he will get to it soon.

In the mean time we have made quite a lot of changes to our repo structure, could you rebase your PR so we can merge it in when the time comes?

2022-11-25 08:03 UTC, cgeorgilakis commented
I have rebased it.

2023-01-20 11:58 UTC, jonkoops commented
@cgeorgilakis I think we are ready to merge this in, could you do another rebase and resolve the conflicts?

2023-01-20 13:31 UTC, mposolda commented
@jonkoops I've closed the PR to the main codebase. I don't think that this new switch should be introduced (See comments on the codebase PR for the details). So I suggest to close this PR as well rather than merging this.

2023-01-20 13:32 UTC, mposolda requested changes
@jonkoops Marked as "Request changes" for now (just in case, so it is not accidentally merged...)

2023-01-20 14:33 UTC, jonkoops commented
I see, @mposolda I mistook this PR and thought it was merged in the main project. I'm closing this PR for the same motivations you outlined there.

2023-01-20 14:33 UTC, closed without merging