added translation for OIDC choices for Client authentication
keycloak/keycloak-ui pull request #3088
Opened 2022-08-09 11:46 UTC by ikhomyn

## Motivation
Fixes #3080 

## Checklist:

- [X] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated

## Additional Notes

2022-08-09 12:06 UTC, jonkoops commented on src/identity-providers/add/OIDCAuthentication.tsx
> +  const clientAuthentications = [
Why move these into the component if they can be defined as a constant outside of it?

2022-08-09 12:06 UTC, jonkoops commented on src/identity-providers/add/OIDCAuthentication.tsx
> +              selections={t(`${value}`)}
Why would the selections need to be translated?

2022-08-09 12:51 UTC, ikhomyn commented on src/identity-providers/add/OIDCAuthentication.tsx
> +              selections={t(`${value}`)}
Hi @jonkoops , yes, you are right, there is not sense. I've updated both suggestions. Thanks!

2022-08-10 05:32 UTC, edewit requested changes

2022-08-10 05:32 UTC, edewit commented on src/identity-providers/add/OIDCAuthentication.tsx
> +  "clientAuth_privatekey_jwt",
Can't change these values as they saved and the backend expects them to be like this

2022-08-10 05:32 UTC, edewit commented on src/identity-providers/add/OIDCAuthentication.tsx
> +  "clientAuth_privatekey_jwt",
It would be better to change the translation keys instead

2022-08-10 08:45 UTC, ikhomyn commented on src/identity-providers/add/OIDCAuthentication.tsx
> +  "clientAuth_privatekey_jwt",
I see. I've changed them back and updated translation keys. Thank you @edewit

2022-08-10 10:52 UTC, edewit approved these changes

2022-08-15 10:37 UTC, jonkoops approved these changes

2022-08-16 10:54 UTC, edewit approved these changes

2022-08-16 10:54 UTC, merged