Issue 3135
keycloak/keycloak-ui pull request #3166
Opened 2022-08-23 09:03 UTC by dominikkawka

2022-08-23 09:58 UTC, jonkoops requested changes

2022-08-23 09:58 UTC, jonkoops commented on cypress/e2e/clients_test.spec.ts
> +  describe.only("Client creation", () => {
```suggestion
  describe("Client creation", () => {
```

2022-08-23 09:58 UTC, jonkoops commented on cypress/e2e/clients_test.spec.ts
> -  describe.only("Roles tab test", () => {
I'm going to introduce a linting rule to prevent this from getting introduced.

2022-08-23 09:58 UTC, jonkoops commented on cypress/support/pages/admin_console/manage/clients/CreateClientPage.ts
> +    cy.get(this.clientConsentScreenText).click();
What are we testing here exactly?

2022-08-23 10:15 UTC, dominikkawka commented on cypress/support/pages/admin_console/manage/clients/CreateClientPage.ts
> +    cy.get(this.clientConsentScreenText).click();
To see if the text box is clickable, although looking at it now it is a little redundant since .should("not.be.disabled") is there

2022-08-26 08:59 UTC, jonkoops approved these changes

2022-08-26 08:59 UTC, jonkoops commented
@dominikkawka could you rebase the PR on `main`?

2022-08-26 12:22 UTC, closed without merging

2022-08-26 12:24 UTC, dominikkawka commented
> @dominikkawka could you rebase the PR on `main`?

It wouldn't let me merge/rebase, it would say it was up to date, I think it would be easier just to make a new PR at this point..