Force refresh of user after save to avoid modal (#3180)
keycloak/keycloak-ui pull request #3187
Opened 2022-08-24 14:31 UTC by kris2kris

## Motivation
Closes #3180 

## Brief Description
The problem is that field stay dirty after save, so I force refresh of user after an update. Maybe there is a better way to reset dirty field, maybe display a spinner instead of form during save.

## Verification Steps
1. Update user firstname and save.
2. Switch to Attributes tab.
3. Do it once again if problem doesn't occurred.

## Checklist:

- [X] Code has been tested locally by PR requester

2022-08-24 14:40 UTC, jonkoops requested changes

2022-08-24 14:40 UTC, jonkoops commented on src/user/UsersTabs.tsx
> +  const [forceFetch, setForceFetch] = useState(false);
We're already using a pattern for this that uses a count to force a refresh. Let's keep that aligned with what we are already doing.

```suggestion
  const [refreshCount, setRefreshCount] = useState(0);
  const refresh = () => setRefreshCount((count) => count + 1);
```

2022-08-24 14:40 UTC, jonkoops commented on src/user/UsersTabs.tsx
> +    [user?.username, forceFetch]
```suggestion
    [user?.username, refreshCount]
```

2022-08-24 14:40 UTC, jonkoops commented on src/user/UsersTabs.tsx
> +        setForceFetch(!forceFetch);
```suggestion
        refresh();
```

2022-08-24 15:21 UTC, kris2kris commented on src/user/UsersTabs.tsx
> +  const [forceFetch, setForceFetch] = useState(false);
It's ok for me, I test with the change and it's still working

2022-08-24 16:12 UTC, jonkoops approved these changes

2022-08-25 07:02 UTC, edewit approved these changes

2022-08-25 07:02 UTC, merged