Fix Keycloak OpenID Connect Identity provider creation
keycloak/keycloak-ui pull request #3255
Opened 2022-09-01 01:12 UTC by cwelchrh

## Motivation
Closes #3252 

## Brief Description
When creating a Keycloak OpenID Connect Identity Provider, the providerId is set to 'oidc' instead of 'keycloak-oidc', resulting in unexpected behavior.

## Verification Steps
1. Master Realm > Identity Providers
2. Select 'Keycloak OpenID Connect'. If there are already IdPs created: Click 'Add provider' dropdown, select 'Keycloak OpenID Connect'
4. Confirm that the header says 'Add Keycloak OpenID Connect provider' instead of 'Add OpenID Connect provider'
5. Fill out form, save.
6. Go back to Master Realm > Identity Providers
7. Confirm the "Provider details" for the provider created says "Keycloak-oidc" instead of "oidc"

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated

2022-09-05 12:04 UTC, edewit commented
@cwelchrh I created a PR on your PR that fixes this issue in a different way could you have a look?

2022-09-05 12:05 UTC, edewit requested changes
see my PR

2022-09-07 05:22 UTC, edewit approved these changes
:+1:

2022-09-12 13:41 UTC, jonkoops requested changes

2022-09-12 13:41 UTC, jonkoops commented on apps/admin-ui/src/identity-providers/add/AddOpenIdConnect.tsx
> +  const { id } = useParams<{ id: string }>();
Can we re-use the `IdentityProviderOidcParams` type here?
```suggestion
  const { id } = useParams<IdentityProviderOidcParams>();
```

2022-09-12 22:57 UTC, cwelchrh commented on apps/admin-ui/src/identity-providers/routes/IdentityProviderOidc.ts
> +export type IdentityProviderOidcParams = { id: OidcType; realm: string };
I'm a bit impartial here. The value represents the ID of the provider, so is changing `OidcType` to `OidcProviderID` more accurate? Are there similar conventions throughout the UI code where provider IDs are referred to as "types"?

2022-09-13 11:21 UTC, jonkoops commented on apps/admin-ui/src/identity-providers/routes/IdentityProviderOidc.ts
> +export type IdentityProviderOidcParams = { id: OidcType; realm: string };
I think `id` more accurately reflects a globally unique identifier, whereas a 'type' is a list of known options. Since in this case it's not really unique (given there are only two options) I prefer the 'type' nomenclature.

2022-09-13 12:46 UTC, jonkoops approved these changes
I went ahead and added the review feedback so we can get this merged :+1:

2022-09-15 09:44 UTC, merged