Add nightly run using nightly builds
keycloak/keycloak-ui pull request #3260
Opened 2022-09-02 07:39 UTC by stianst

2022-09-02 09:25 UTC, jonkoops requested changes

2022-09-02 09:25 UTC, jonkoops commented on .github/workflows/cypress.yml
>      needs: setup
This dependency now no longer exists.

2022-09-02 09:57 UTC, stianst commented on .github/workflows/cypress.yml
>      needs: setup
Not following, could you elaborate?

2022-09-06 12:18 UTC, ssilvert commented on .github/workflows/cypress.yml
>      needs: setup
@stianst FYI Jon is out this week.

2022-09-06 13:35 UTC, jonkoops commented on .github/workflows/cypress.yml
>      needs: setup
This job [depends on](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idneeds) the `setup` job, which was removed [here](https://github.com/keycloak/keycloak-ui/pull/3260/files/713a363e8fd83af660212479f4fa74d3beb2d5da#diff-5da9a41590fb261de0e464c95862528100c42c77dffad53b7c6de228b6afd2bdL8).

2022-09-07 06:32 UTC, stianst commented on .github/workflows/cypress.yml
>      needs: setup
LOL, of course ;)

Fixed this now by having a need on both jobs, then running it if either passes. A bit weird, but have tested it works (https://github.com/stianst/playground/actions/workflows/main.yml)

2022-09-12 10:02 UTC, jonkoops approved these changes

2022-09-12 10:04 UTC, jonkoops commented on .github/workflows/cypress.yml
>      needs: setup
Oh yeah, that makes sense. Even if it's a bit counterintuitive.

2022-09-12 11:22 UTC, jonkoops approved these changes

2022-09-12 11:24 UTC, stianst commented on .github/workflows/cypress.yml
> +            wget -q https://github.com/keycloak/keycloak/releases/download/nightly/keycloak-999-SNAPSHOT.tar.gz
```suggestion
            gh release -R keycloak/keycloak download nightly -p keycloak-999-SNAPSHOT.tar.gz
```

2022-09-13 08:58 UTC, jonkoops approved these changes

2022-09-13 08:58 UTC, merged