account ui
keycloak/keycloak-ui pull request #3385
Opened 2022-09-23 13:59 UTC by edewit

- initial version
- added initial version of masthead lib
- changed to let account-ui use masthead
- fixed build
- added default dropdown items
- added wireit
- * added way to load data using fetch * initial AccountPage
- finished account page
- added signing in page
- added delete credential
- added alerts
- added device activity page

Initial version of the account ui introduces a lot of new concepts, to review it might be easier to take a look at the individual commits

2022-09-26 19:08 UTC, ssilvert approved these changes
I think we should go ahead and merge this as a baseline.  But I'll give others a chance to chime in.

2022-09-27 09:36 UTC, jonkoops requested changes

2022-09-27 09:36 UTC, jonkoops commented on .gitignore
> +dist/
Let's add this to a dedicated `.gitignore` in `apps/account-ui` like we're already doing for the Admin UI. Reason for this is that Keycloak JS cannot fully ignore the `dist` directory, as it contains files that should be checked in.

2022-09-27 09:36 UTC, jonkoops commented on apps/account-ui/cypress/cypress.config.mjs
> +import webpackPreprocessor from "@cypress/webpack-batteries-included-preprocessor";
I was thinking to put the E2E tests in it's own app (e.g. `account-ui-e2e`).

2022-09-27 09:36 UTC, jonkoops commented on apps/account-ui/cypress/cypress.config.mjs
> +import webpackPreprocessor from "@cypress/webpack-batteries-included-preprocessor";
We might reduce duplication by creating a base config file for Cypress in the root of the project and extend it here and in the Admin UI (see [Cypress docs](https://www.cypress.io/blog/2020/06/18/extending-the-cypress-config-file/)).

2022-09-27 09:36 UTC, jonkoops commented on apps/account-ui/package.json
> +{
There should only be a single package lock file in the root of the project, this one should be removed. (commented here because diff is too large on the other file).

2022-09-27 09:36 UTC, jonkoops commented on apps/account-ui/package.json
> +  "dependencies": {
Small nit: the `wireit` section is directly under the `scripts` section in the other projects.

2022-09-27 09:36 UTC, jonkoops commented on apps/account-ui/package.json
> +  "wireit": {
All of these tasks should also rely on `keycloak-js`'s build.

2022-09-27 09:36 UTC, jonkoops commented on apps/account-ui/src/app.module.css
> +img.logo {
Let's not make this selector overly specific.
```suggestion
.logo {
```

2022-09-27 09:36 UTC, jonkoops commented on apps/account-ui/public/resources/content.json
> +[
Several of the fields in this JSON file are never actually used. Perhaps we can remove them for now instead of giving the illusion that these do anything.

2022-09-27 09:36 UTC, jonkoops commented on apps/account-ui/package.json
> +  "dependencies": {
Are we sure all of these dependencies are being used?

2022-09-27 09:36 UTC, jonkoops commented on apps/account-ui/public/resources/content.json
> +[
Why are we doing `content.json`? I thought we were going to skip this customization for now?

2022-09-27 09:36 UTC, jonkoops commented on libs/masthead/vite.config.ts
> +      formats: ["es", "umd"],
Let's not build this as a UMD library.
```suggestion
      formats: ["es"],
```

2022-09-27 09:36 UTC, jonkoops commented on libs/masthead/vite.config.ts
> +      },
We should not be exposing these globals.
```suggestion
```

2022-09-27 09:37 UTC, jonkoops commented
I've left a partial review, but I feel like this PR is way too big. I'd like to see this split up into some smaller PRs.

2022-09-27 10:44 UTC, edewit commented on apps/account-ui/package.json
> +  "dependencies": {
yes

2022-09-27 10:45 UTC, edewit commented on apps/account-ui/package.json
> +  "wireit": {
well masthead relies on `keycloak-js`

2022-09-27 10:46 UTC, edewit commented on apps/account-ui/public/resources/content.json
> +[
we have to have the structure of the menu somewhere right?

2022-09-27 10:46 UTC, edewit commented on apps/account-ui/src/app.module.css
> +img.logo {
it's needed otherwise it doesn't override patternfly

2022-09-27 19:39 UTC, ssilvert commented
> I've left a partial review, but I feel like this PR is way too big. I'd like to see this split up into some smaller PRs.

Normally I would agree wholeheartedly.  And if @edewit has an easy way to split it up that would be nice.

But there are also advantages of this port-and-refactor approach where we have quite a bit of working code to start with.  Then any of us can start sending PRs to improve it.

2022-09-28 05:36 UTC, edewit commented
I'll close this and create a PR per commit that is 13 PRs

2022-09-28 05:36 UTC, closed without merging

2022-09-28 05:51 UTC, edewit commented on apps/account-ui/public/resources/content.json
> +[
it's only `modulePath` that was use do to dynamically load scripts

2022-09-29 20:03 UTC, ssilvert commented
> I'll close this and create a PR per commit that is 13 PRs

@edewit I hope you are being sarcastic.  I was fine with it the way it was.

2022-10-03 11:39 UTC, edewit commented
Yes, I am, created a new PR that just only introduces the new modules. After that I'll create another PR that adds all the code