added credential table for user federation
keycloak/keycloak-ui pull request #3491
Opened 2022-10-06 07:07 UTC by edewit

same as in the old console when credentials are federated by ldap

2022-10-06 09:00 UTC, jonkoops requested changes

2022-10-06 09:00 UTC, jonkoops commented on apps/admin-ui/src/user/UserCredentials.tsx
> +            hasIcon={true}
```suggestion
            hasIcon
```

2022-10-06 09:00 UTC, jonkoops commented on apps/admin-ui/src/user/user-credentials/FederatedCredentials.tsx
> +                        access.hasAccess("view-realm")
Should this link not be disabled instead when there is no access?

2022-10-06 10:50 UTC, edewit commented on apps/admin-ui/src/user/user-credentials/FederatedCredentials.tsx
> +                        access.hasAccess("view-realm")
yeah guess that's better this is what the old console did... but I'll change it

2022-10-18 12:30 UTC, jonkoops commented
@edewit the tests seem to keep failing, can you take a look?

2022-11-04 08:48 UTC, closed without merging