Added alphabetically listing the policies - Issue-2032
keycloak/keycloak-ui pull request #3556
Opened 2022-10-11 16:44 UTC by agagancarczyk

## Motivation
Closes https://github.com/keycloak/keycloak-ui/issues/2032

## Verification Steps
1. Go to `Clients > Client details > Authorization > Policies > Create policy`.
2. Verify that the policies are sorted alphabetically. 

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated

2022-10-11 21:03 UTC, jonkoops requested changes

2022-10-11 21:03 UTC, jonkoops commented on apps/admin-ui/src/clients/authorization/NewPolicyDialog.tsx
> +    () => localeSort(policyProviders!, mapByKey("name")),
It's possible for `policyProviders` to be `undefined`. Let's try to take that into account.
```suggestion
    () => policyProviders ? localeSort(policyProviders, mapByKey("name")) : [],
```

2022-10-12 08:29 UTC, agagancarczyk commented on apps/admin-ui/src/clients/authorization/NewPolicyDialog.tsx
> +    () => localeSort(policyProviders!, mapByKey("name")),
sure, thanks @jonkoops

2022-10-17 10:32 UTC, jonkoops approved these changes

2022-10-17 13:09 UTC, merged