Improve flow for testing e-mail server settings
keycloak/keycloak-ui pull request #3619
Opened 2022-10-21 11:59 UTC by jonkoops

This PR aims to improve the flow for testing the connection of the e-mail server configured in the realm settings. When testing these settings it is required that the currently signed-in user has an e-mail address configured, so that a test e-mail can be sent.

Previously when either saving these settings or testing the connection the user would be prompted with a modal dialog (see below) to confirm their e-mail address. The issue with this method is that it implicitly configures the entered e-mail address as the address of the currently logged-in user, leading to confusion (see #3593).

![A screenshot showing the dialog asking the user to enter their e-mail address.](https://user-images.githubusercontent.com/695720/197188087-c1354999-6c47-4d2b-8b98-196aae26caff.png)

Besides poorly conveying that this implicitly configures the e-mail address of the user (instead of just sending an e-mail to the entered address), it also uses the same message when saving the settings. This might lead to further confusion as the user now gets presented with texts related to testing a connection.

To resolve this issue I have opted to remove the aforementioned dialog entirely, from both the 'Save' and 'Test connection' flows. In fact, it is not even required to configure an e-mail address when simply saving these settings (the old console does this as well).

When the user attempts to test the connection without having an e-mail address configured they will find the 'Test connection' button disabled. To avoid confusion an alert has been added below the button, notifying the user their e-mail address is yet to be configured. A link to their account settings is also presented to allow configuration of said e-mail address.

![A screenshot of the alert presented to the user, asking them to configure their e-mail address.](https://user-images.githubusercontent.com/695720/197189638-d613792c-558f-4366-9c15-a55e0c8e1c39.png)

Once the user has configured their e-mail address and returns to test the connection they will find that the 'Test connection' button is now enabled. Another alert is presented underneath the button to notify the user that an e-mail will be sent to their configured address.

![A screenshot showing the enabled 'test connection' button and accompanying alert.](https://user-images.githubusercontent.com/695720/197190378-b1a45962-b127-46d9-a0b1-4daff73e7834.png)

The UX that is being presented here is something that I came up with, so it will have to be vetted by @xianli123 before merging.

Closes #3593

2022-10-21 12:05 UTC, jonkoops commented
@lostunicorn I'd also like to know if this resolves the issue as you have reported it in #3614. Could you also take a look at this solution?

2022-10-21 12:18 UTC, ssilvert requested changes
I like this solution a lot.  It's a big improvement on the old console too.

2022-10-21 12:18 UTC, ssilvert commented on apps/admin-ui/public/resources/en/realm-settings.json
> +    "withoutEmail": "To test the connection you must first configure an e-mail address for your user.",
@jonkoops Let's make the `withoutEmail` as clear as `withEmail`.  Suggested change:
```suggestion
    "withoutEmail": "To test the connection you must configure an e-mail address for the current user ({{userName}}).",
```

2022-10-21 12:26 UTC, lme-atolcd commented
@jonkoops IMHO this PR totally makes sens to me as an end-user. The message alerting that an e-mail address must be configured for the current user is much more clear than the previous modal dialog. This will also prevent the username from being changed without the current user noticing it.

2022-10-21 12:42 UTC, jonkoops commented on apps/admin-ui/public/resources/en/realm-settings.json
> +    "withoutEmail": "To test the connection you must first configure an e-mail address for your user.",
Done, I've also changed `withEmail` to be more consistent with the flow of `withoutEmail`.

2022-10-21 13:39 UTC, jonkoops commented
Thanks a lot for the quick feedback @lme-atolcd :+1:

2022-10-21 18:46 UTC, ssilvert approved these changes
Looks good.

2022-10-23 19:01 UTC, lostunicorn commented
> @lostunicorn I'd also like to know if this resolves the issue as you have reported it in #3614. Could you also take a look at this solution?

yes, this would solve my issue 🙂
As the email address of the user is no longer stored during the connection test, the username would not be changed, regardless of the registrationEmailAsUsername setting in the realm for witch the smtp configuration is tested.

2022-10-24 05:57 UTC, edewit approved these changes

2022-10-24 09:46 UTC, jonkoops commented
Incorporated some feedback from @xianli123 to give the alerts a different style.

2022-10-24 09:46 UTC, xianli123 approved these changes

2022-10-24 09:46 UTC, jonkoops commented
Thanks @lostunicorn, it helps a lot knowing this works for you as well.

2022-10-24 11:43 UTC, merged

2022-10-24 11:45 UTC, jonkoops commented
I've merged this work in, it should come along with the release of Keycloak 20 (which is expected this week).