when using timeout we don't need onTimeout
keycloak/keycloak-ui pull request #3641
Opened 2022-10-25 08:40 UTC by edewit

this fixes the issue with the notification timeout being cumulative
see: https://github.com/patternfly/patternfly-react/issues/8064

## Motivation

## Brief Description

## Verification Steps

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated

## Additional Notes

2022-10-25 10:42 UTC, ssilvert approved these changes

2022-10-25 13:59 UTC, jonkoops commented
Oh damn, nice find Erik!

2022-10-25 14:02 UTC, jonkoops requested changes
Since we are not passing this callback anymore, how is the state in the `AlertProvider` updated? Seems like it could be a memory leak since it will continue to hold all previous alerts in the state.

2022-10-26 14:58 UTC, edewit commented
Yes @jonkoops you make a good point. How about I change it so that "expired" alerts get removed at some interval?

2022-10-27 10:39 UTC, jonkoops commented
Yeah, that seems like a good solution to me.

2022-10-27 11:24 UTC, jonkoops approved these changes

2022-10-27 12:00 UTC, merged