Tooltip for post logout redirect uri needs updating for Keycloak issue 14884
keycloak/keycloak-ui pull request #3699
Opened 2022-11-02 16:24 UTC by douglaspalmer

Closes #3698

2022-11-02 16:27 UTC, douglaspalmer commented
Should be merged after https://github.com/keycloak/keycloak/pull/15298

2022-11-02 17:26 UTC, sschu commented on apps/admin-ui/public/resources/en/clients-help.json
> +  "validPostLogoutRedirectURIs": "Valid URI pattern a browser can redirect to after a successful logout. A value of '+' will use the list of valid redirect uris. A value of '-' will use an empty list
See my comment here: https://github.com/keycloak/keycloak/pull/15298#discussion_r1012072751

2022-11-02 18:17 UTC, ssilvert requested changes
We have a problem with the other languages because they aren't getting updated.  I'll ping the rest of the UI team to see if they have any ideas about what we should do in this case.

2022-11-02 19:53 UTC, ssilvert commented
@douglaspalmer I think what we need to do for now is just to remove that key for the other languages.  Then it will default to English and the community will send us the proper translations later.

2022-11-03 10:07 UTC, sschu commented
I could provide German translations once we agreed on a text.

2022-11-03 18:15 UTC, ssilvert commented
@jonkoops I agree.  Please create an issue for it.

@sschu @douglaspalmer Since the text is not agreed upon I'm going to close this PR.  I'd prefer to have a new PR when the dependent PR is merged and the text is finalized.  At that time, we can provide translations for those languages where we are proficient.  Also, @douglaspalmer, when you create the new PR, please remove the keys for those languages that don't have a translation.

2022-11-03 18:15 UTC, closed without merging

2022-11-04 11:23 UTC, jonkoops commented
@ssilvert Done, see #3712. Feel free to add to the requirements.