added user profile attributes to user detail screen
keycloak/keycloak-ui pull request #3762
Opened 2022-11-14 09:37 UTC by edewit

- initial version
- select
- removed static validators and fixed rendering of options
- removed double form element
- fixed cast and added empty option
- added groups
- filter the config attr. from the attributes form

## Motivation

## Brief Description

## Verification Steps

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated

## Additional Notes

2022-11-16 10:12 UTC, jonkoops requested changes

2022-11-16 10:12 UTC, jonkoops commented on apps/admin-ui/src/user/UserAttributes.tsx
> +      );
`Object.assign()` will mutate the original reference (in this case `user.attributes`), you might want to provide an empty object as the first argument to prevent this.
```suggestion
      const attributes = Object.assign(
        {},
        user.attributes || {},
        keyValueToArray(attributeForm.attributes!)
      );
```

2022-11-16 10:12 UTC, jonkoops commented on apps/admin-ui/src/user/UserForm.tsx
> +                type="text"
This is already the default type, so this property can be omitted.
```suggestion
```

2022-11-16 10:12 UTC, jonkoops commented on apps/admin-ui/src/user/UserForm.tsx
> +                  id={"kc-user-email-verified"}
```suggestion
                  id="kc-user-email-verified"
```

2022-11-16 10:12 UTC, jonkoops commented on apps/admin-ui/src/user/UserForm.tsx
> +                  aria-label={t("emailVerified")}
Since the field is already associated with the label from the control, there should be no need to add this attribute.
```suggestion
```

2022-11-16 10:12 UTC, jonkoops commented on apps/admin-ui/src/user/UserForm.tsx
> +              aria-label={t("firstName")}
```suggestion
```

2022-11-16 10:12 UTC, jonkoops commented on apps/admin-ui/src/user/UserForm.tsx
> +              type="text"
```suggestion
```

2022-11-16 10:12 UTC, jonkoops commented on apps/admin-ui/src/user/UserForm.tsx
> +              type="text"
```suggestion
```

2022-11-16 10:12 UTC, jonkoops commented on apps/admin-ui/src/user/UserForm.tsx
> +              aria-label={t("lastName")}
```suggestion
```

2022-11-16 10:12 UTC, jonkoops commented on apps/admin-ui/src/user/UserForm.tsx
> +            id={"temporaryLocked"}
```suggestion
            id="temporaryLocked"
```

2022-11-16 10:12 UTC, jonkoops commented on apps/admin-ui/src/user/UserForm.tsx
> +            aria-label={t("temporaryLocked")}
```suggestion
```

2022-11-16 10:12 UTC, jonkoops commented on apps/admin-ui/src/user/UserProfileFields.tsx
> +    Object.prototype.hasOwnProperty.call(
```suggestion
    Object.hasOwn(
```

2022-11-16 10:12 UTC, jonkoops commented on apps/admin-ui/src/user/UserProfileFields.tsx
> +          type="text"
```suggestion
```

2022-11-16 10:12 UTC, jonkoops commented on apps/admin-ui/src/user/UserProfileFields.tsx
> +          aria-label={attribute.name}
```suggestion
```

2022-11-16 10:12 UTC, jonkoops commented on apps/admin-ui/src/user/UsersTabs.tsx
> +        const createdUser = await adminClient.users.create(formUser);
Instead of mutating `formUser` (which might have unintended side-effects), you could spread it into the call directly.  It's not used anywhere else, so in-lining it like this is fine.
```suggestion
        const createdUser = await adminClient.users.create({
          ...formUser,
          groups: addedGroups.map((group) => group.path!)
        });
```

2022-11-17 11:39 UTC, jonkoops approved these changes

2022-11-17 16:14 UTC, merged

2022-11-24 09:04 UTC, Ekouyoja commented
Hello,
Thanks for your work, maybe it's a stupid question but how can we know which version of keycloak will include your commit ?

2022-11-24 10:22 UTC, jonkoops commented
We will assign a milestone to the issue when we do a release. This will likely end up in Keycloak 21.