do not show enabled and required for email and username
keycloak/keycloak-ui pull request #3766
Opened 2022-11-14 14:23 UTC by edewit

fixes: #3612

## Motivation

## Brief Description

## Verification Steps

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated

## Additional Notes

2022-11-14 16:09 UTC, jonkoops requested changes

2022-11-14 16:09 UTC, jonkoops commented on apps/admin-ui/src/realm-settings/NewAttributeSettings.tsx
> +    obj: Record<string, unknown>[] | Record<string, any> | undefined
Can we get rid of the `any` type here? Using `unknown` will force us to derive a proper type.

2022-11-14 16:09 UTC, jonkoops commented on apps/admin-ui/src/realm-settings/NewAttributeSettings.tsx
> +      prevValidations[currentValidations.key] =
If we are populating an object like this, why just populate it with a loop?

2022-11-16 09:21 UTC, edewit commented on apps/admin-ui/src/realm-settings/NewAttributeSettings.tsx
> +      prevValidations[currentValidations.key] =
this is a loop no?

2022-11-16 12:35 UTC, jonkoops requested changes

2022-11-16 12:35 UTC, jonkoops commented on apps/admin-ui/src/realm-settings/NewAttributeSettings.tsx
> +type IndexedAnnotationsType = {
Can we drop the `Type` suffix? It's kind of an anti-pattern, unless it's really needed.

```suggestion
type IndexedAnnotations = {
````

2022-11-16 12:35 UTC, jonkoops commented on apps/admin-ui/src/realm-settings/NewAttributeSettings.tsx
> +export type IndexedValidationsType = {
Likewise here.
```suggestion
export type IndexedValidations = {
```

2022-11-16 12:35 UTC, jonkoops commented on apps/admin-ui/src/realm-settings/NewAttributeSettings.tsx
> +  const convert = (obj: Record<string, any> | undefined) =>
I think we should split out the convert for the validations and annotations into separate functions. That should allow us to write them type-safe.

2022-11-16 12:35 UTC, jonkoops commented on apps/admin-ui/src/realm-settings/NewAttributeSettings.tsx
> +      {} as Record<string, any>
This type can be improved now, no? Also, it can be passed in as a generic to `.reduce()` instead.

2022-11-16 12:35 UTC, jonkoops commented on apps/admin-ui/src/realm-settings/user-profile/attribute/AddValidatorDialog.tsx
> +          <TableComposable aria-label="validators-table">
This is not a human readable string, so let's remove it.
```suggestion
          <TableComposable>
```

2022-11-16 12:35 UTC, jonkoops commented on apps/admin-ui/src/realm-settings/user-profile/attribute/AttributeValidations.tsx
> +          <TableComposable aria-label="validators-table">
Same here, not readable for humans.
```suggestion
          <TableComposable>
```

2022-11-16 14:17 UTC, jonkoops approved these changes

2022-11-16 14:19 UTC, merged