Readmes updates
keycloak/keycloak-ui pull request #3807
Opened 2022-11-18 12:50 UTC by agagancarczyk

## Motivation
Updated all READMEs in order to bring more clarity to the project and sub-projects structures. 

## Verification Steps
N/A

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated

2022-11-21 13:09 UTC, edewit approved these changes

2022-11-21 14:46 UTC, jonkoops requested changes

2022-11-21 14:46 UTC, jonkoops commented on README.md
> +    └── tsconfig.json
I don't think we need to list all of these files, they have little relevance to the directory structure.
```suggestion
```

2022-11-21 14:46 UTC, jonkoops commented on README.md
> +    ├── libs                    # Keycloak libraries
It would be nice to have the libraries listed here as well, with a nice description.

2022-11-21 14:46 UTC, jonkoops commented on README.md
> +    │   └── keycloak-server
Can we add comments here as well with the description of each directory?

2022-11-21 14:46 UTC, jonkoops commented on apps/account-ui/README.md
> +## Repository structure
I think there is no need to describe the directory structure here, it follows the conventions of the Vite template. Perhaps a callout to the [Vite guide](https://vitejs.dev/guide/) here would be enough.

2022-11-21 14:46 UTC, jonkoops commented on apps/admin-ui/README.md
> +## Repository structure
Same here, I think callouts to the Vite and Cypress guides would be enough.

2022-11-21 14:46 UTC, jonkoops commented on apps/keycloak-server/README.md
> +## Repository structure
I also think there is no need for the directory structure here.

2022-11-21 14:46 UTC, jonkoops commented on apps/keycloak-server/README.md
> +### Keycloak server config scripts
This is not really relevant as these scripts are ran through NPM, and the rest is just implementation details.

2022-11-30 10:23 UTC, agagancarczyk commented on README.md
> +    └── tsconfig.json
Thanks, yeah, I was thinking the same but wanted to see what you would think of it.

2022-11-30 15:51 UTC, agagancarczyk commented
hi @jonkoops could you please review it again? Let's finalize it. Thanks!

2022-12-01 14:19 UTC, merged