Use cryptoInfo to populate key type dropdowns.
keycloak/keycloak-ui pull request #3818
Opened 2022-11-22 21:40 UTC by douglaspalmer

closes #3616

2022-11-23 08:03 UTC, mposolda commented
@douglaspalmer The change looks good to me, Thanks!

@ssilvert Are you please also able to review or delegate to someone from UI team to review?

2022-11-23 15:04 UTC, jonkoops requested changes

2022-11-23 15:04 UTC, jonkoops commented on apps/admin-ui/src/clients/keys/ImportKeyDialog.tsx
> +  const baseFormats = useServerInfo().cryptoInfo?.supportedKeystoreTypes;
Providing a default value here will remove the need to use optional chaining later on.
```suggestion
  const baseFormats = useServerInfo().cryptoInfo?.supportedKeystoreTypes ?? [];
```

2022-11-23 15:04 UTC, jonkoops commented on apps/admin-ui/src/clients/keys/Keys.tsx
> +export const getFileExt = (keystoreType: string | undefined) => {
This could be re-used, as mentioned before.

2022-11-23 15:04 UTC, jonkoops commented on apps/admin-ui/src/clients/keys/Keys.tsx
>          new Blob([keyStore], { type: "application/octet-stream" }),
Just wondering, is this the correct mime type for all of the extensions?

2022-11-23 16:49 UTC, douglaspalmer commented on apps/admin-ui/src/clients/keys/ExportSamlKeyDialog.tsx
> +};
@jonkoops any suggestion as to where the shared code should live?

2022-11-23 19:19 UTC, douglaspalmer commented on apps/admin-ui/src/clients/keys/Keys.tsx
>          new Blob([keyStore], { type: "application/octet-stream" }),
@jonkoops there appears to be a mime type application/x-pkcs12 but I don't know how much it's used.

2022-11-24 13:40 UTC, edewit commented on apps/admin-ui/src/clients/keys/Keys.tsx
>          new Blob([keyStore], { type: "application/octet-stream" }),
this will at least make your browser download it, I think we use this already in other places

2022-11-24 15:34 UTC, douglaspalmer commented on apps/admin-ui/src/clients/keys/Keys.tsx
>          new Blob([keyStore], { type: "application/octet-stream" }),
@edewit this isn't part of the pull request; it's the original code.

2022-11-24 15:49 UTC, jonkoops commented on apps/admin-ui/src/clients/keys/ExportSamlKeyDialog.tsx
> +};
Yeah, that seems fine to me 👍

2022-11-24 16:00 UTC, jonkoops approved these changes
LGTM. We can handle the mime type as a separate issue.

2022-11-24 16:59 UTC, merged