JKS keystore type available as default option in FIPS mode Closes #3977
keycloak/keycloak-ui pull request #3986
Opened 2022-12-09 22:40 UTC by douglaspalmer

Removed default values.

2022-12-13 08:45 UTC, mposolda requested changes
@douglaspalmer The change seems to be in right direction, but there is test error and it looks that it is regression of this PR?

I guess the `defaultValue` may be still set, but possibly to the 1st option in the available options. So something like `defaultValue=options[0]` (Just pseudo-code for illustration, I don't have clue what is correct syntax :-) )

At least, if it is not possible to set the default value right away, it should be probably ok to set to the 1st option right before it is saved (Button `Save` is clicked)?

I can be wrong but I guess that the test error is caused by the fact that HTTP request to server fails because `keystoreType` is not set in the REST request to server. So when the `keystoreType` is set to the 1st option, the HTTP request sent to the server should have `keystoreType` correctly set to the 1st option (if it was not changed by the admin by explicitly selecting different option).

2022-12-14 08:52 UTC, jonkoops commented
@mposolda If I read the issue correctly then the default should be `PKCS12` in a FIPS environment. However is `JKS` not still the best option in a non-FIPS environment? Or should the default always be `PKCS12` no matter the environment?

2022-12-14 09:00 UTC, mposolda commented
@jonkoops The default should be the 1st option available. In the typical (non-FIPS) environment, it is usually `JKS`. In the FIPS environment, it can be usually `PKCS12`. However even in some FIPS environment (for example with BCFIPS library set to "Approved mode"), the PKCS12 may not be available and hence default should be `BCFKS`.

Simply said, really the 1st option available from combobox.

2022-12-14 16:59 UTC, douglaspalmer commented
> @jonkoops The default should be the 1st option available. In the typical (non-FIPS) environment, it is usually `JKS`. In the FIPS environment, it can be usually `PKCS12`. However even in some FIPS environment (for example with BCFIPS library set to "Approved mode"), the PKCS12 may not be available and hence default should be `BCFKS`.
> 
> Simply said, really the 1st option available from combobox.

Isn't the first option what we get when we don't set a default? From my cursory testing that appears to be the case.

2022-12-15 14:37 UTC, jonkoops commented on apps/admin-ui/cypress/support/pages/admin-ui/manage/clients/client_details/tabs/KeysTab.ts
> +    cy.get("#archiveFormat").click();
Added an id selector here instead of querying using an attribute selector.

2022-12-15 14:37 UTC, jonkoops commented on apps/admin-ui/cypress/support/pages/admin-ui/manage/clients/client_details/tabs/KeysTab.ts
> +    cy.findAllByRole("option").contains(archiveFormat).click();
Restored `archiveFormat` here, instead of hard-coding one of the options.

2022-12-15 14:39 UTC, jonkoops commented on apps/admin-ui/src/clients/keys/GenerateKeyDialog.tsx
> +          defaultValue={supportedKeystoreTypes[0]}
Added the first option of the `supportedKeystoreTypes` here, as not providing a default will log warnings.

2022-12-15 14:39 UTC, jonkoops commented on apps/admin-ui/src/clients/keys/ImportKeyDialog.tsx
> +    defaultValue: formats[0],
Same here, I added the first option as a default.

2022-12-15 14:39 UTC, jonkoops approved these changes

2022-12-15 14:41 UTC, jonkoops commented
@mposolda @douglaspalmer I added a commit with my review feedback and implementation based on what was discussed here. Could you take a look and let me know if it looks and behaves as you would expect?

@edewit would you mind reviewing this PR as I added some of my own code?

2022-12-15 14:55 UTC, edewit approved these changes
:+1:

2022-12-15 16:30 UTC, douglaspalmer commented on apps/admin-ui/cypress/support/pages/admin-ui/manage/clients/client_details/tabs/KeysTab.ts
> +    cy.get("#archiveFormat").click();
Do we still need to modify the test at all since you've set defaults? I think it was only failing because I removed the default.

2022-12-15 16:30 UTC, douglaspalmer commented on apps/admin-ui/cypress/support/pages/admin-ui/manage/clients/client_details/tabs/KeysTab.ts
> +    cy.findAllByRole("option").contains(archiveFormat).click();
Do we still need to modify the test at all since you've set defaults?

2023-01-02 15:34 UTC, merged

2023-01-02 15:41 UTC, mposolda commented
@jonkoops Thanks for your work on this!