Allow add/remove user with only query-users role.
keycloak/keycloak-ui pull request #4013
Opened 2022-12-12 20:30 UTC by ssilvert

## Motivation
Fixes https://github.com/keycloak/keycloak-ui/issues/3965

## Brief Description
Also needs back end change.  See https://github.com/keycloak/keycloak/pull/15967

## Verification Steps
See #3965 

Simpler way than what is in the issue is to grant permissions with a user policy instead of a group policy.

## Additional Notes
Need to wait for back end change to be merged.

2022-12-12 20:33 UTC, ssilvert commented on apps/admin-ui/src/user/UserForm.tsx
> +      {isFeatureEnabled(Feature.DeclarativeUserProfile) ? (
@edewit Wonder if this change is OK?  The problem I had was that the `userProfileEnabled` attribute would be undefined if the user does not have the `view-realm` role.

2022-12-13 06:53 UTC, edewit approved these changes

2022-12-13 06:53 UTC, edewit commented on apps/admin-ui/src/user/UserForm.tsx
> +      {isFeatureEnabled(Feature.DeclarativeUserProfile) ? (
there have been more issues like this, I guess it's fine

2022-12-13 20:58 UTC, ssilvert commented
API change is now merged into keycloak/keycloak.  Removed hold.

2023-01-03 15:52 UTC, jonkoops commented on apps/admin-ui/src/user/UserForm.tsx
> +      {isFeatureEnabled(Feature.DeclarativeUserProfile) ? (
Are we sure this is ok? I think that for these fields to be presented the feature must also be enabled in the realm settings, otherwise what is the purpose of that switch?

2023-01-03 15:52 UTC, jonkoops requested changes
Not quite sure if we can remove the condition from the `UserForm`.

2023-01-06 09:14 UTC, edewit commented on apps/admin-ui/src/user/UserForm.tsx
> +      {isFeatureEnabled(Feature.DeclarativeUserProfile) ? (
the problem is that we can't check the realm attributes when you don't have rights

2023-01-12 13:25 UTC, ssilvert commented
> Not quite sure if we can remove the condition from the `UserForm`.

Anyway, I had to add an extra check for `undefined` so that the screen would be rendered the old way and the tests will pass.  Now that part is equivalent to what we had before and it fixes the case where the user does not have the `view-realm` role.

2023-01-16 10:39 UTC, jonkoops commented
@ssilvert there are some merge conflicts on the PR, could you resolve them?

2023-01-16 10:47 UTC, jonkoops requested changes

2023-01-16 10:47 UTC, jonkoops commented on apps/admin-ui/src/user/UserForm.tsx
> +      realm.attributes.userProfileEnabled === "true" ? (
The first statement here is redundant. `realm?.attributes?.userProfileEnabled === "true"` will already implicitly assert that `realm.attributes.userProfileEnabled` is not `undefined`.

So unless I am missing something the following code should yield the same result.
```suggestion
      realm?.attributes?.userProfileEnabled === "true" ? (
```

2023-01-16 14:13 UTC, closed without merging