added tooltip and css to group name
keycloak/keycloak-ui pull request #4044
Opened 2022-12-15 12:50 UTC by edewit

fixes: #3970

## Motivation

## Brief Description

## Verification Steps

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated

## Additional Notes

2022-12-15 14:46 UTC, jonkoops requested changes

2022-12-15 14:46 UTC, jonkoops commented on apps/admin-ui/src/groups/components/group-tree.css
> +.keycloak_groups_treeview .pf-c-tree-view__node {
Perhaps we can use a CSS module for this one? Vite has support for it built-in for it.

2022-12-15 14:46 UTC, jonkoops commented on apps/admin-ui/src/groups/components/GroupTree.tsx
> +            to={`/${realm}/groups/${joinPath(...groups.map((g) => g.id!))}`}
Any chance this could be a link function?

2022-12-15 14:46 UTC, jonkoops commented on apps/admin-ui/src/groups/components/GroupTree.tsx
> +            key={group.id}
Why would we need a `key` here?
```suggestion
```

2022-12-15 15:04 UTC, edewit commented on apps/admin-ui/src/groups/components/group-tree.css
> +.keycloak_groups_treeview .pf-c-tree-view__node {
we don't use that anywhere yet, if we want to use that I feel that we should migrate everything at once

2022-12-15 15:06 UTC, edewit commented on apps/admin-ui/src/groups/components/GroupTree.tsx
> +            to={`/${realm}/groups/${joinPath(...groups.map((g) => g.id!))}`}
unfortunately that is not an option, as these ids can be any number

2022-12-16 06:49 UTC, edewit commented on apps/admin-ui/src/groups/components/group-tree.css
> +.keycloak_groups_treeview .pf-c-tree-view__node {
one problem we should solve though, before we can switch, is how can we still override these styles

2023-01-03 16:31 UTC, jonkoops commented on apps/admin-ui/src/groups/components/GroupTree.tsx
> +            to={`/${realm}/groups/${joinPath(...groups.map((g) => g.id!))}`}
Yeah, I figured as much. But thanks for checking.

2023-01-03 16:31 UTC, jonkoops commented on apps/admin-ui/src/groups/components/group-tree.css
> +.keycloak_groups_treeview .pf-c-tree-view__node {
Fair enough. We have #2873 to track this.

2023-01-03 16:32 UTC, merged