Add attributes tab to realm settings
keycloak/keycloak-ui pull request #4046
Opened 2022-12-15 20:55 UTC by antikalk

## Motivation
Add a possibility to edit realm attributes in realm settings.

## Brief Description
Added an additional tab to the realm settings. Unfortunately I was not able to use the key-value-convert, as realm attributes are represented differently on API level than other attributes (string: string instead of string: string[]). **This also leads to the effect that when adding an attribute with a key that is already present the value is just overwritten.** 

Any suggestions are welcome :)

## Verification Steps
1. Go to `Realm Settings >> Attributes`.
2. Create a new attribute with key 'test' and value 'value'.
3. Click save.
4. Verify that the new attribute is available.

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated

## Additional Notes
![image](https://user-images.githubusercontent.com/1793007/207964508-fc6f3579-211f-46a8-acaf-14675f01ee39.png)

2022-12-20 12:29 UTC, edewit commented
I can see how this is useful for custom attributes, but implemented like this it also shows attributes that have "proper" input fields

2022-12-21 02:13 UTC, xianli123 commented
Hi @stianst, could you please take a look at this issue? I am not sure about the use cases of this feature. Do we need to list all realm attributes and allow users to customize attributes? Thanks.

2023-01-01 11:02 UTC, xgp commented
@edewit Agree with your point on attributes with "proper" input fields. Do we have a definitive list somewhere of those attributes? If we could not show (or show with some kind of warning) the keys for which there are "official" attributes.

However, even as written, plus some kind of "expert mode" warning at the top, I think this would be an excellent addition, as it really helps with custom attributes, and is helpful to extension writers that use custom attributes for configuration.

2023-01-05 09:54 UTC, xianli123 commented
Hi @xgp In this pr, you mentioned:
> Add a possibility to edit realm attributes in realm settings.

Could you please explain what realm attributes you want to edit or view? Thanks!

2023-01-05 13:03 UTC, xgp commented
@xianli123 I build several Keycloak extensions that use realm attributes for configuration. It would be great to have a UI for configuring those attributes.

2023-01-05 13:16 UTC, stianst commented
In it's current shape I don't think we can add this for two reasons:

1. Custom realm attributes are a very specialised thing, as such the attributes tab should maybe be added under some "advanced settings" tab or something. We may also want it to be something that has to be explicitly enabled, perhaps as a feature flag, or something a custom extension that uses custom realm attributes can enable
2. We should not expose "internal" attributes as it is doing right now. We don't really have a reliable way to know what are internal and what are custom attributes currently, as strictly speaking they are all internal, as we don't strictly support custom realm attributes, that's just something folks do. In general we prefer customisation at the provider level (for example authenticators and mappers can have their own config)

All in all I think this is a lot more effort than it is worth to do in a proper way, and I would argue that instead custom providers should be configurable by themselves.

2023-01-05 13:16 UTC, stianst requested changes
I'm not in favour of adding this, especially not in its current form

2023-01-06 08:20 UTC, xianli123 commented
@xgp Thanks 👍

2023-01-10 13:46 UTC, closed without merging

2023-01-10 13:47 UTC, ssilvert commented
Sorry.  We can not accept this PR for the reasons stated above.