draft: Turn protocol to required property
keycloak/keycloak-ui pull request #4047
Opened 2022-12-15 23:26 UTC by AmusedShadow

## Motivation

## Brief Description

## Verification Steps

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated

## Additional Notes

2022-12-16 06:45 UTC, edewit reviewed
Nice, it's good to have better types

2022-12-16 06:45 UTC, edewit commented on libs/keycloak-admin-client/src/defs/ssoProtocols.ts
> +export type SSOProtocol = typeof SSOProtocol[keyof typeof SSOProtocol];
this could be simpler right?
```suggestion
export type SSOProtocol = "openid-connect" | "saml" | "docker-v2";
```

2022-12-16 17:25 UTC, AmusedShadow commented on libs/keycloak-admin-client/src/defs/ssoProtocols.ts
> +export type SSOProtocol = typeof SSOProtocol[keyof typeof SSOProtocol];
This is a possibility but, in case we are adding new values to the SSO const we need to add them manually also to the type definition ore else it would differ from each other and lead to a syntax issue. 

May we can add your suggestion as commit above and link the official typescript docu that explains the behavior of this single line. 

In my first days with this line I also thought it is a little bit over complex but we stepped in to many problems that the 'setter' const does not fit at the end to the type validator ... so we replaced the direkt string types by this and based type on configuration.

2022-12-19 09:37 UTC, edewit commented on libs/keycloak-admin-client/src/defs/ssoProtocols.ts
> +export type SSOProtocol = typeof SSOProtocol[keyof typeof SSOProtocol];
what kind of problems did you run into? we use this everywhere, didn't have any problems. And when the const changes the type needs to change as well, but that is true for your version. WDYT @jonkoops

2022-12-19 21:21 UTC, AmusedShadow commented on libs/keycloak-admin-client/src/defs/ssoProtocols.ts
> +export type SSOProtocol = typeof SSOProtocol[keyof typeof SSOProtocol];
```
 const SSOProtocol = {
    openIDConnect: "openid-connect",
    saml:"saml",
    docker: "docker-v2" 
}
 type SSOProtocol = typeof SSOProtocol[keyof typeof SSOProtocol];

const x: SSOProtocol = "openid-connect" // Not a good idea at all. It is a REST-API value and should be represented by ENUM
console.log(SSOProtocol.openIDConnect) // Should be used becasue it could be ignored if value of openIDConnect will change


type SSOProtocolAlternative = "openid-connect" | "saml" | "docker-v2";

const y:SSOProtocolAlternative = "openid-connect" // Same so fare 
console.log(SSOProtocolAlternative.openid-connect) // ERROR! Could not found
```

On a fluid API or an API on change, it will always cause trouble in case you hard code property-values that are constructed as ENUM values within the REST API in your Client Code. 
In case you are using `SSOProtocolAlternative` your whole code need a refactor on multiple positions (see test cases, I switched from direct using "openeid-connect" to `SSOProtocol.openIDconnect`)  when the API changes.
Ok to be honest, this part of API should be relative stable, but ... 

In case you are using `SSOProtocol.openIDconnect` you just change the value of a property in 1 line, and everything will transpire correctly and because it is defined within the lib you are consuming all user of nom just need an update of package :)

2022-12-19 22:13 UTC, AmusedShadow commented
@edewit @jonkoops 
May you have a look to this Discussion: 
https://github.com/keycloak/keycloak/discussions/16086

May this should be part of PR? It is a missing property ... but I am not sure if it is just for the ui or also for the server itself ...

2023-01-16 12:33 UTC, jonkoops requested changes

2023-01-16 12:33 UTC, jonkoops commented on libs/keycloak-admin-client/src/utils/constants.ts
> +export const defaultBaseUrl = "http://127.0.0.1:8080";
This should not have been changed, please revert it.
```suggestion
export const defaultBaseUrl = "http://127.0.0.1:8180";
```

2023-01-16 12:36 UTC, jonkoops requested changes

2023-01-16 12:36 UTC, jonkoops commented on libs/keycloak-admin-client/test/constants.ts
> +  password: "change_me",
Please revert this to what it was before.

2023-01-18 11:10 UTC, jonkoops commented
Turning this into a draft until we have reached some consensus on how to land this.

2023-02-11 21:42 UTC, AmusedShadow commented on libs/keycloak-admin-client/src/utils/constants.ts
> +export const defaultBaseUrl = "http://127.0.0.1:8080";
Sorry for this.

2023-02-11 21:48 UTC, AmusedShadow commented on libs/keycloak-admin-client/src/defs/ssoProtocols.ts
> +export type SSOProtocol = typeof SSOProtocol[keyof typeof SSOProtocol];
No sorry, I will not do that. If you prefer to have it based on string literals, that's entirely your own decision within the community, which has already done a really good job! But from my point of view, besides KIS and Clean Code, the rule is everywhere: Never hardcode values. It may be common use to implement things this way, also because string enums have slipped in only in TS >= 2.4 and until today somehow do not quite fit into the overall concept. 
There are things I don't train myself to avoid after years of practice. :) You now know the problem and a solution. Then do it yourself with pleasure in your own way.

2023-02-11 21:48 UTC, closed without merging