User events configuration fine tuning - #1562
keycloak/keycloak-ui pull request #4076
Opened 2022-12-20 15:22 UTC by agagancarczyk

## Motivation
Closes #1562

## Verification Steps

1. Go to `Realm settings >> Events >> User events settings`.
2. Verify that the header title `User events configuration` has been removed.
3. Set `Save events` to `On` and observe that the list of events only displays when the button `Save` is clicked.
4. In the events list, select the `three dots` button in the first row and verify that button is now reading `Remove`.
5. Go to `Admin events settings` and verify that the header title `Admin events configuration` has been removed.

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated

2022-12-21 07:17 UTC, edewit requested changes

2022-12-21 07:17 UTC, edewit commented on apps/admin-ui/src/realm-settings/event-config/EventsTab.tsx
> +      setEventsConfigSaved(true);
this isn't right, it means that when I come back to the page I have to save the config again to see the adjust the messages.

2022-12-21 17:38 UTC, agagancarczyk commented on apps/admin-ui/src/realm-settings/event-config/EventsTab.tsx
> +      setEventsConfigSaved(true);
thanks @edewit I overlooked this, but I think I found a fix. Please review it again. Thanks!

2022-12-22 07:48 UTC, edewit approved these changes

2022-12-22 08:33 UTC, merged