add openid as default scope and add option to set custom scopes
keycloak/keycloak-ui pull request #4078
Opened 2022-12-21 10:57 UTC by Axenu

## Motivation
Since the release of keycloak 20.0.0 it is required to specify the scope when authenticating. This is easily discovered when calling the /userinfo endpoint in keycloak with an auth token that is created without the scope.
https://www.keycloak.org/docs/latest/upgrading/#userinfo-endpoint-changes

## Brief Description
I have added a default scope as "openid" to solve above problem. 
I have also added an optional parameter for users who wish to set their own scope.

## Verification Steps
1. get an auth token by calling
```const keycloakAdmin = new KeycloakAdmin({<some settings>})
keycloakAdmin.auth(authInfo)```
2. Use the accessToken created above and call the `protocol/openid-connect/userinfo` endpoint.3. 
3. Before this PR it results in a 403.

## Checklist:

- [x] Code has been tested locally by PR requester
- [N/A] User-visible strings are using the react-i18next framework (useTranslation)
- [N/A] Help has been implemented
- [N/A] axe report has been run and resulting a11y issues have been resolved
- [x] Unit tests have been created/updated

2023-01-02 12:12 UTC, jonkoops requested changes
Running this code against the latest nightly version of the Keycloak server gives me the following failures:

![A screenshot of the failing tests](https://user-images.githubusercontent.com/695720/210229655-dd6ff52a-7d2e-4682-b233-dbc53246b9cd.png)

Any idea what might be causing this?

2023-01-02 12:42 UTC, jonkoops commented
Also thanks for including tests with your changes, it's very much appreciated.

2023-01-03 09:45 UTC, Axenu commented
The nightly build failing tests looks very odd. I assume this is due to some change with the new version of keycloak. I will check to see if I can find some way forward.

2023-01-03 10:19 UTC, Axenu commented
So it seems like I missed it. I have changed it so that my PR doesn't change the default scope param, but rather just ads it as optional. This works for nightly as well.

2023-01-16 12:42 UTC, jonkoops approved these changes
LGTM

2023-01-16 12:42 UTC, jonkoops commented
Tests are all passing, I am merging this in. Thanks for your contribution @Axenu!

2023-01-16 12:43 UTC, merged