Use React Router v6 for the routable tabs
keycloak/keycloak-ui pull request #4113
Opened 2023-01-02 18:08 UTC by jonkoops

Converts the routable tabs code to use the latest version of React Router. This is one of the last pieces needed finish the migration to the new React Router.

2023-01-03 11:18 UTC, jonkoops commented
Converting this to a draft as it results in too many errors and should probably be split into several PRs.

2023-01-06 09:21 UTC, edewit requested changes

2023-01-06 09:21 UTC, edewit commented on apps/admin-ui/src/clients/ClientDetails.tsx
> +  const advancedTab = useTab("advanced");
can't we do this like we did before? These variables are only used one time

2023-01-06 11:54 UTC, jonkoops commented on apps/admin-ui/src/clients/ClientDetails.tsx
> +  const advancedTab = useTab("advanced");
Because we need to call them as hooks, and the tabs render conditionally.

2023-01-06 14:58 UTC, jonkoops commented
Closing this as all the work has been merged in other PRs.

2023-01-06 14:58 UTC, closed without merging