Client assertion signature configuration of identity broker is missing on new security admin console
keycloak/keycloak-ui pull request #4145
Opened 2023-01-07 17:26 UTC by i7a7467

## Motivation
keycloak/keycloak#14021

## Brief Description
Closes #4144 

## Verification Steps
No response

## Checklist:

- [x] Code has been tested locally by PR requester
- [x] User-visible strings are using the react-i18next framework (useTranslation)
- [x] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [x] Unit tests have been created/updated

## Additional Notes
I changed this one along with WRITING_TEST.md.

2023-01-09 21:04 UTC, ssilvert commented on apps/admin-ui/cypress/support/pages/admin-ui/manage/identity_providers/ProviderBaseAdvancedSettingsPage.ts
> +  algorithmNotSpecified = "Algorithm not specified",
Need to use i18n key you defined in the json file.

2023-01-14 11:22 UTC, i7a7467 commented on apps/admin-ui/cypress/support/pages/admin-ui/manage/identity_providers/ProviderBaseAdvancedSettingsPage.ts
> +  algorithmNotSpecified = "Algorithm not specified",
@ssilvert 
Thanks reply.
I do not believe it is necessary to use i18n key since this part of the code is the source of comparison for the cypress test.
Could you please provide some more details?

2023-01-17 10:54 UTC, jonkoops requested changes

2023-01-17 10:54 UTC, jonkoops commented on apps/admin-ui/cypress/e2e/identity_providers_oidc_test.spec.ts
> +      //Cliient assertion signature algorithm
```suggestion
      // Client assertion signature algorithm
```

2023-01-17 10:54 UTC, jonkoops commented on apps/admin-ui/cypress/support/pages/admin-ui/manage/identity_providers/ProviderBaseAdvancedSettingsPage.ts
> +  algorithmNotSpecified = "Algorithm not specified",
I'd say there is no need to do this for the tests, this is application code.

2023-01-17 10:54 UTC, jonkoops commented on apps/admin-ui/src/identity-providers/add/OIDCAuthentication.tsx
> +              aria-label={t("signatureAlgorithm")}
I think we can drop this label as the `Select` already has a `FormGroup` associated with it.

2023-01-17 10:54 UTC, jonkoops commented on apps/admin-ui/src/identity-providers/add/OIDCAuthentication.tsx
> +              <>
Do we really need a fragment here?

2023-01-17 10:54 UTC, jonkoops commented on apps/admin-ui/src/identity-providers/add/OIDCAuthentication.tsx
> +                  ></SelectOption>
This element can be self-closing.
```suggestion
                  />
```

2023-01-17 10:54 UTC, jonkoops commented
Looks good @i7a7467, just a couple of small nits.

2023-01-22 13:59 UTC, i7a7467 commented on apps/admin-ui/cypress/e2e/identity_providers_oidc_test.spec.ts
> +      //Cliient assertion signature algorithm
Thanks. I fixed it.

2023-01-22 14:00 UTC, i7a7467 commented on apps/admin-ui/src/identity-providers/add/OIDCAuthentication.tsx
> +              aria-label={t("signatureAlgorithm")}
You are correct. I fixed it.

2023-01-22 14:01 UTC, i7a7467 commented on apps/admin-ui/src/identity-providers/add/OIDCAuthentication.tsx
> +                  ></SelectOption>
I fixed it.

2023-01-22 14:02 UTC, i7a7467 commented on apps/admin-ui/src/identity-providers/add/OIDCAuthentication.tsx
> +              <>
I deleted fragment.
But I want to be able to choose `Algorithm not specified` , so I made some modifications.

2023-01-22 14:19 UTC, i7a7467 commented
@jonkoops 
Thanks for writing details. Could you confirm if?

2023-01-23 12:56 UTC, jonkoops approved these changes
I can't vouch for the Japanese translations, but everything looks good to me :+1:

2023-01-23 13:17 UTC, merged