client registration
keycloak/keycloak-ui pull request #4250
Opened 2023-01-24 14:07 UTC by edewit

fixes: #3638

- initial version
- added create and list page
- added client registration policy add screen
- fixed error text
- added details and delete
- added authenticated tab
- revert
- added info tab text
- added test and delete button on view header

## Motivation

## Brief Description

## Verification Steps

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated

## Additional Notes

2023-01-24 16:09 UTC, jonkoops requested changes

2023-01-24 16:09 UTC, jonkoops commented on apps/admin-ui/cypress/support/pages/admin-ui/manage/clients/ClientRegistrationPage.ts
> +    cy.get(`#${name}`).click();
Should we not be using a test id here instead?

2023-01-24 16:09 UTC, jonkoops commented on apps/admin-ui/src/clients/routes/AddRegistrationProvider.ts
> +import { lazy } from "react";
Can we split this into two separate route files?

2023-01-26 12:21 UTC, edewit commented on apps/admin-ui/cypress/support/pages/admin-ui/manage/clients/ClientRegistrationPage.ts
> +    cy.get(`#${name}`).click();
I would if `data-testid` would be on the rendered html, but it isn't

2023-01-26 12:52 UTC, jonkoops approved these changes

2023-02-03 11:56 UTC, merged