moved common controls to ui shared
keycloak/keycloak-ui pull request #4274
Opened 2023-01-27 14:47 UTC by edewit

## Motivation

## Brief Description

## Verification Steps

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated

## Additional Notes

2023-01-27 16:28 UTC, jonkoops requested changes

2023-01-27 16:28 UTC, jonkoops commented on libs/ui-shared/package.json
> +      ],
I don't believe we have a dependency on `keycloak-js` here, let's remove this one.
```suggestion
```

2023-01-27 16:28 UTC, jonkoops commented on libs/ui-shared/src/main.ts
> +export { AlertProvider, useAlerts } from "./alerts/Alerts";
We should also export the prop types here so they can be re-used.

2023-01-30 07:05 UTC, edewit commented on libs/ui-shared/src/main.ts
> +export { AlertProvider, useAlerts } from "./alerts/Alerts";
right

2023-01-30 16:52 UTC, jonkoops requested changes
@edewit looks like there are some build errors, can you take a look?

2023-02-07 11:29 UTC, jonkoops approved these changes

2023-02-07 11:29 UTC, merged