added null check
keycloak/keycloak-ui pull request #4305
Opened 2023-02-01 15:27 UTC by edewit

fixes: #4295

## Motivation

## Brief Description

## Verification Steps

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated

## Additional Notes

2023-02-01 16:26 UTC, jonkoops requested changes

2023-02-01 16:26 UTC, jonkoops commented on apps/admin-ui/cypress/e2e/client_authorization_test.spec.ts
> +    masthead.checkNotificationMessage("Resource successfully updated", true);
I believe `true` is the default here, so it can be omitted.
```suggestion
    masthead.checkNotificationMessage("Resource successfully updated");
```

2023-02-02 08:47 UTC, edewit commented on apps/admin-ui/src/clients/advanced/AdvancedSettings.tsx
> +              name={convertAttributeNameToForm("attributes.acr.loa.map")}
this is a bug the register happens in the `KeyValueInput`

2023-02-02 11:43 UTC, jonkoops approved these changes

2023-02-02 11:44 UTC, jonkoops commented on apps/admin-ui/src/clients/advanced/AdvancedSettings.tsx
> +              name={convertAttributeNameToForm("attributes.acr.loa.map")}
Hmmm, okay looks a bit strange. But sure.

2023-02-02 13:20 UTC, jonkoops commented on apps/admin-ui/cypress/component/KeyValueInput.cy.tsx
> +import {
This has been fixed under #4307.

2023-02-02 14:35 UTC, merged