Consistent language fallbacks for admin ui theme
keycloak/keycloak-ui pull request #4395
Opened 2023-02-14 15:53 UTC by danielFesenmeyer

- i18next does not support variants, hence the prio of messages is as follows (RL = realm localization, T = Theme i18n files): RL \<region> > T \<region> > RL \<language> > T \<language> > RL en > T en
- remove the param useRealmDefaultLocaleFallback=true from the call to /admin/realms/{realm}/localization/{locale}, because otherwise realm localization texts of the realm default language would overwrite more specific texts from translation files (and unnecessary data will be loaded)
- add cypress test i18n_test.spec.ts, which checks the fallback implementation
- log a warning instead of an error, when messages for some languages/namespaces cannot be loaded (the page will probably work with fallbacks in that case)

Closes #4390

## Motivation
This is the admin ui part of https://github.com/keycloak/keycloak/pull/17076

## Brief Description
Changes the prio of localized messages as follows (RL = realm localization, T = Theme i18n files): RL \<region> > T \<region> > RL \<language> > T \<language> > RL en > T en

## Verification Steps
See the tests in i18n_test.spec.ts

## Checklist:

- [x] Code has been tested locally by PR requester
- [x] User-visible strings are using the react-i18next framework (useTranslation)
- [not relevant] Help has been implemented
- [?] axe report has been run and resulting a11y issues have been resolved
- [x] Unit tests have been created/updated

## Additional Notes
Only works completely when this Keycloak PR has been merged: https://github.com/keycloak/keycloak/pull/17076

2023-02-15 11:53 UTC, edewit commented on apps/admin-ui/src/i18n.ts
> +      }/localization/{{lng}}`;
shouldn't we keep this `useRealmDefaultLocaleFallback` option? see https://github.com/keycloak/keycloak/issues/11851

2023-02-15 11:57 UTC, edewit commented
@ssilvert can you have a look at this

2023-02-15 14:42 UTC, danielFesenmeyer commented on apps/admin-ui/src/i18n.ts
> +      }/localization/{{lng}}`;
This is no longer needed, because the postProcessor is no longer used (for why, see my comments in i18n.ts, function addInterceptorForGetResource). The english (default) translation is now loaded in a separate request and applied, if a more specific translation is not available.

If the param `useRealmDefaultLocaleFallback` was still used, it would have the following disadvantages:
- english realm localization texts would overwrite more specific translations from the json files. For example, an english realm localization text would overwrite a german text from the json files, if locale de was requested. (The english realm localization text should only overwrite the english text from the json files.)
- unnecessary network traffic: due to loading of the same data multiple times - english texts would be both loaded for locale en, and for the user requested locale (e.g. de)

2023-02-15 15:59 UTC, jonkoops commented
Converting this to a draft since it requires upstream work to be merged first.

2023-02-15 16:08 UTC, danielFesenmeyer commented
Just fixed some formatting errors in the PR description.

2023-02-15 19:56 UTC, ssilvert requested changes
Overall, I like what you are doing here.  Very nice.

2023-02-15 19:56 UTC, ssilvert commented on apps/admin-ui/src/i18n.ts
> +  const i18nStore = i18n.store as any;
We try to stay away from the `any` type.  Looks like you may need to declare some new types?

2023-02-21 14:29 UTC, danielFesenmeyer commented on apps/admin-ui/src/i18n.ts
> +  const i18nStore = i18n.store as any;
Ok, I got rid of the `any` and declared a type instead.

Furthermore, I've adjusted the tests in order to run with cypress 12 (turned out they didn't).
Some of them will still fail until the upstream PR is merged: https://github.com/keycloak/keycloak/pull/17076

2023-03-14 12:02 UTC, jonkoops commented
Hi @danielFesenmeyer, we have moved the Admin UI to the main Keycloak repo as part of our mono-repoing efforts. Could you open up a PR with the same changes there? If you have a PR already open for this feature feel free to add the changes there.

2023-03-14 12:02 UTC, closed without merging

2023-03-14 13:06 UTC, danielFesenmeyer commented
@jonkoops Thanks for the hint - I will create a corresponding PR at the keycloak repo.

2023-03-14 13:23 UTC, danielFesenmeyer commented
@jonkoops: Does that mean that the account UI is now also developed in the keycloak repo again?

2023-03-14 19:55 UTC, ssilvert commented
@danielFesenmeyer Just to be clear, V2 of the account console still lives in themes/src/main/resources/theme/keycloak.v2/account.

V3 is the one in the /js directory.  V3 is not shipping with keycloak yet.