revert use of randomUUID
keycloak/keycloak-ui pull request #4457
Opened 2023-02-24 17:04 UTC by edewit

fixes: #4442

## Motivation

## Brief Description

## Verification Steps

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated

## Additional Notes

2023-02-24 17:34 UTC, SamTV12345 commented
Is [this](https://www.npmjs.com/package/uuid) library not a better replacement for the problem? We currently hope that Math.random()*1000 doesn't generate the same number. UUIDs are [specified](https://www.rfc-editor.org/rfc/rfc4122) and should never appear twice.

2023-02-27 08:26 UTC, edewit commented
@SamTV12345 the number is used to identify an alert that stays on the page for 8 seconds so at most you have 3 of those at the same time. Even if they have the same number by change the worst that is going to happen is that one disappears a bit quicker. I don't think it's worth adding an entire library to prevent that.

2023-02-27 11:17 UTC, SamTV12345 commented
@edewit It is just a bit cleaner with UUIDs. But I guess it won't make a difference in practice. I created another pr that solves the problem with the library included.

2023-02-28 16:39 UTC, jonkoops requested changes

2023-02-28 16:39 UTC, jonkoops commented on apps/admin-ui/src/components/dynamic/MapComponent.tsx
> +const generateId = () => Math.floor(Math.random() * 100);
Can we put this into a single utility function and re-use it across the project?

2023-02-28 16:51 UTC, jonkoops commented
Perhaps a better solution for generating IDs in React components would be to use the [`useId()`](https://beta.reactjs.org/reference/react/useId) hook which was introduced in React 18.

2023-03-03 10:48 UTC, jonkoops approved these changes

2023-03-03 12:32 UTC, jonkoops approved these changes

2023-03-03 12:57 UTC, merged